// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescoredns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CoreDNSZoneFileArgs extends com.pulumi.resources.ResourceArgs {

    public static final CoreDNSZoneFileArgs Empty = new CoreDNSZoneFileArgs();

    @Import(name="contents")
    private @Nullable Output<String> contents;

    public Optional<Output<String>> contents() {
        return Optional.ofNullable(this.contents);
    }

    @Import(name="domain")
    private @Nullable Output<String> domain;

    public Optional<Output<String>> domain() {
        return Optional.ofNullable(this.domain);
    }

    @Import(name="string")
    private @Nullable Output<String> string;

    public Optional<Output<String>> string() {
        return Optional.ofNullable(this.string);
    }

    private CoreDNSZoneFileArgs() {}

    private CoreDNSZoneFileArgs(CoreDNSZoneFileArgs $) {
        this.contents = $.contents;
        this.domain = $.domain;
        this.string = $.string;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CoreDNSZoneFileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CoreDNSZoneFileArgs $;

        public Builder() {
            $ = new CoreDNSZoneFileArgs();
        }

        public Builder(CoreDNSZoneFileArgs defaults) {
            $ = new CoreDNSZoneFileArgs(Objects.requireNonNull(defaults));
        }

        public Builder contents(@Nullable Output<String> contents) {
            $.contents = contents;
            return this;
        }

        public Builder contents(String contents) {
            return contents(Output.of(contents));
        }

        public Builder domain(@Nullable Output<String> domain) {
            $.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        public Builder string(@Nullable Output<String> string) {
            $.string = string;
            return this;
        }

        public Builder string(String string) {
            return string(Output.of(string));
        }

        public CoreDNSZoneFileArgs build() {
            return $;
        }
    }

}
