// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescoredns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CoreDNSDeploymentArgs extends com.pulumi.resources.ResourceArgs {

    public static final CoreDNSDeploymentArgs Empty = new CoreDNSDeploymentArgs();

    /**
     * Optionally disable the main deployment and its respective resources.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Optionally disable the main deployment and its respective resources.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Name of the deployment if deployment.enabled is true. Otherwise the name of an existing deployment for the autoscaler or HPA to target.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the deployment if deployment.enabled is true. Otherwise the name of an existing deployment for the autoscaler or HPA to target.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private CoreDNSDeploymentArgs() {}

    private CoreDNSDeploymentArgs(CoreDNSDeploymentArgs $) {
        this.enabled = $.enabled;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CoreDNSDeploymentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CoreDNSDeploymentArgs $;

        public Builder() {
            $ = new CoreDNSDeploymentArgs();
        }

        public Builder(CoreDNSDeploymentArgs defaults) {
            $ = new CoreDNSDeploymentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Optionally disable the main deployment and its respective resources.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Optionally disable the main deployment and its respective resources.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param name Name of the deployment if deployment.enabled is true. Otherwise the name of an existing deployment for the autoscaler or HPA to target.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the deployment if deployment.enabled is true. Otherwise the name of an existing deployment for the autoscaler or HPA to target.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public CoreDNSDeploymentArgs build() {
            return $;
        }
    }

}
