// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescoredns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetescoredns.inputs.CoreDNSPrometheusMonitorArgs;
import com.pulumi.kubernetescoredns.inputs.CoreDNSPrometheusServiceArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CoreDNSPrometheusArgs extends com.pulumi.resources.ResourceArgs {

    public static final CoreDNSPrometheusArgs Empty = new CoreDNSPrometheusArgs();

    @Import(name="monitor")
    private @Nullable Output<CoreDNSPrometheusMonitorArgs> monitor;

    public Optional<Output<CoreDNSPrometheusMonitorArgs>> monitor() {
        return Optional.ofNullable(this.monitor);
    }

    @Import(name="service")
    private @Nullable Output<CoreDNSPrometheusServiceArgs> service;

    public Optional<Output<CoreDNSPrometheusServiceArgs>> service() {
        return Optional.ofNullable(this.service);
    }

    private CoreDNSPrometheusArgs() {}

    private CoreDNSPrometheusArgs(CoreDNSPrometheusArgs $) {
        this.monitor = $.monitor;
        this.service = $.service;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CoreDNSPrometheusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CoreDNSPrometheusArgs $;

        public Builder() {
            $ = new CoreDNSPrometheusArgs();
        }

        public Builder(CoreDNSPrometheusArgs defaults) {
            $ = new CoreDNSPrometheusArgs(Objects.requireNonNull(defaults));
        }

        public Builder monitor(@Nullable Output<CoreDNSPrometheusMonitorArgs> monitor) {
            $.monitor = monitor;
            return this;
        }

        public Builder monitor(CoreDNSPrometheusMonitorArgs monitor) {
            return monitor(Output.of(monitor));
        }

        public Builder service(@Nullable Output<CoreDNSPrometheusServiceArgs> service) {
            $.service = service;
            return this;
        }

        public Builder service(CoreDNSPrometheusServiceArgs service) {
            return service(Output.of(service));
        }

        public CoreDNSPrometheusArgs build() {
            return $;
        }
    }

}
