// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescoredns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CoreDNSRBACArgs extends com.pulumi.resources.ResourceArgs {

    public static final CoreDNSRBACArgs Empty = new CoreDNSRBACArgs();

    /**
     * If true, create &amp; use RBAC resources
     * 
     */
    @Import(name="create")
    private @Nullable Output<Boolean> create;

    /**
     * @return If true, create &amp; use RBAC resources
     * 
     */
    public Optional<Output<Boolean>> create() {
        return Optional.ofNullable(this.create);
    }

    /**
     * The name of the ServiceAccount to use. If not set and create is true, a name is generated using the fullname template.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the ServiceAccount to use. If not set and create is true, a name is generated using the fullname template.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * If true, create and use PodSecurityPolicy
     * 
     */
    @Import(name="pspEnable")
    private @Nullable Output<Boolean> pspEnable;

    /**
     * @return If true, create and use PodSecurityPolicy
     * 
     */
    public Optional<Output<Boolean>> pspEnable() {
        return Optional.ofNullable(this.pspEnable);
    }

    private CoreDNSRBACArgs() {}

    private CoreDNSRBACArgs(CoreDNSRBACArgs $) {
        this.create = $.create;
        this.name = $.name;
        this.pspEnable = $.pspEnable;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CoreDNSRBACArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CoreDNSRBACArgs $;

        public Builder() {
            $ = new CoreDNSRBACArgs();
        }

        public Builder(CoreDNSRBACArgs defaults) {
            $ = new CoreDNSRBACArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param create If true, create &amp; use RBAC resources
         * 
         * @return builder
         * 
         */
        public Builder create(@Nullable Output<Boolean> create) {
            $.create = create;
            return this;
        }

        /**
         * @param create If true, create &amp; use RBAC resources
         * 
         * @return builder
         * 
         */
        public Builder create(Boolean create) {
            return create(Output.of(create));
        }

        /**
         * @param name The name of the ServiceAccount to use. If not set and create is true, a name is generated using the fullname template.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the ServiceAccount to use. If not set and create is true, a name is generated using the fullname template.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param pspEnable If true, create and use PodSecurityPolicy
         * 
         * @return builder
         * 
         */
        public Builder pspEnable(@Nullable Output<Boolean> pspEnable) {
            $.pspEnable = pspEnable;
            return this;
        }

        /**
         * @param pspEnable If true, create and use PodSecurityPolicy
         * 
         * @return builder
         * 
         */
        public Builder pspEnable(Boolean pspEnable) {
            return pspEnable(Output.of(pspEnable));
        }

        public CoreDNSRBACArgs build() {
            return $;
        }
    }

}
