# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .core_dns import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "kubernetes-coredns",
  "mod": "index",
  "fqn": "pulumi_kubernetes_coredns",
  "classes": {
   "kubernetes-coredns:index:CoreDNS": "CoreDNS"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "kubernetes-coredns",
  "token": "pulumi:providers:kubernetes-coredns",
  "fqn": "pulumi_kubernetes_coredns",
  "class": "Provider"
 }
]
"""
)
