// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescoredns;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.kubernetescoredns.CoreDNSArgs;
import com.pulumi.kubernetescoredns.Utilities;
import com.pulumi.kubernetescoredns.outputs.ReleaseStatus;
import javax.annotation.Nullable;

/**
 * Enable fast and flexible in-cluster DNS.
 * 
 */
@ResourceType(type="kubernetes-coredns:index:CoreDNS")
public class CoreDNS extends com.pulumi.resources.ComponentResource {
    /**
     * Detailed information about the status of the underlying Helm deployment.
     * 
     */
    @Export(name="status", refs={ReleaseStatus.class}, tree="[0]")
    private Output<ReleaseStatus> status;

    /**
     * @return Detailed information about the status of the underlying Helm deployment.
     * 
     */
    public Output<ReleaseStatus> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CoreDNS(java.lang.String name) {
        this(name, CoreDNSArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CoreDNS(java.lang.String name, @Nullable CoreDNSArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CoreDNS(java.lang.String name, @Nullable CoreDNSArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("kubernetes-coredns:index:CoreDNS", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static CoreDNSArgs makeArgs(@Nullable CoreDNSArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? CoreDNSArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
