// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ChartCertManager.Inputs
{

    public sealed class CoreDNSImageArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Image pull policy.
        /// </summary>
        [Input("pullPolicy")]
        public Input<string>? PullPolicy { get; set; }

        [Input("pullSecrets")]
        private InputList<string>? _pullSecrets;

        /// <summary>
        /// Specify container image pull secrets.
        /// </summary>
        public InputList<string> PullSecrets
        {
            get => _pullSecrets ?? (_pullSecrets = new InputList<string>());
            set => _pullSecrets = value;
        }

        /// <summary>
        /// The image repository to pull from.
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        /// <summary>
        /// The image tag to pull from.
        /// </summary>
        [Input("tag")]
        public Input<string>? Tag { get; set; }

        public CoreDNSImageArgs()
        {
        }
    }
}
