// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCoreDNS.Inputs
{

    public sealed class CoreDNSDeploymentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optionally disable the main deployment and its respective resources.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Name of the deployment if deployment.enabled is true. Otherwise the name of an existing deployment for the autoscaler or HPA to target.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public CoreDNSDeploymentArgs()
        {
        }
        public static new CoreDNSDeploymentArgs Empty => new CoreDNSDeploymentArgs();
    }
}
