// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCoreDNS.Inputs
{

    public sealed class CoreDNSServiceArgs : Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// Annotations to add to service.
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        /// <summary>
        /// IP address to assign to service.
        /// </summary>
        [Input("clusterIP")]
        public Input<string>? ClusterIP { get; set; }

        [Input("externalIPs")]
        private InputList<string>? _externalIPs;

        /// <summary>
        /// External IP addresses.
        /// </summary>
        public InputList<string> ExternalIPs
        {
            get => _externalIPs ?? (_externalIPs = new InputList<string>());
            set => _externalIPs = value;
        }

        /// <summary>
        /// Enable client source IP preservation.
        /// </summary>
        [Input("externalTrafficPolicy")]
        public Input<string>? ExternalTrafficPolicy { get; set; }

        /// <summary>
        /// IP address to assign to load balancer (if supported).
        /// </summary>
        [Input("loadBalancerIP")]
        public Input<string>? LoadBalancerIP { get; set; }

        /// <summary>
        /// The name of the Service. If not set, a name is generated using the fullname template.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public CoreDNSServiceArgs()
        {
        }
    }
}
