// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCoreDNS.Inputs
{

    public sealed class CoreDNSServerPluginArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// if the plugin supports extra block style config, supply it here
        /// </summary>
        [Input("configBlock")]
        public Input<string>? ConfigBlock { get; set; }

        /// <summary>
        /// name of plugin, if used multiple times ensure that the plugin supports it!
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// list of parameters after the plugin
        /// </summary>
        [Input("parameters")]
        public Input<string>? Parameters { get; set; }

        public CoreDNSServerPluginArgs()
        {
        }
        public static new CoreDNSServerPluginArgs Empty => new CoreDNSServerPluginArgs();
    }
}
