// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCoreDNS.Inputs
{

    public sealed class CoreDNSPrometheusArgs : Pulumi.ResourceArgs
    {
        [Input("monitor")]
        public Input<Inputs.CoreDNSPrometheusMonitorArgs>? Monitor { get; set; }

        [Input("service")]
        public Input<Inputs.CoreDNSPrometheusServiceArgs>? Service { get; set; }

        public CoreDNSPrometheusArgs()
        {
        }
    }
}
